name: burt
dependencies:
- biopython=1.65=np19py27_0
- dateutil=2.1=py27_2
- django=1.7.3=py27_0
- gunicorn=19.1.0=py27_0
- ipython=2.3.1=py27_0
- ipython-notebook=2.3.1=py27_0
- jinja2=2.7.3=py27_1
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- numpy=1.9.1=py27_0
- openssl=1.0.1k=0
- pandas=0.15.2=np19py27_0
- pastedeploy=1.5.2=py27_1
- patsy=0.3.0=np19py27_0
- pip=6.0.6=py27_0
- python=2.7.9=1
- pytz=2014.9=py27_0
- pyzmq=14.5.0=py27_0
- readline=6.2=2
- scipy=0.15.1=np19py27_0
- setuptools=12.0.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- tk=8.5.15=0
- tornado=4.0.2=py27_0
- zeromq=4.0.4=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - django-extensions==1.5.0
  - django-grappelli==2.6.3
  - django-sslify-admin==0.5.0
  - python-dateutil==1.5
  - uwsgi==2.0.9
  - psycopg2==2.6
  - django-bootstrap3==5.1.1
